# Generated by Django 2.2.7 on 2024-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0005_auto_20240319_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teranium_project/media'),
        ),
    ]
