# Generated by Django 2.2.7 on 2024-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0006_auto_20240319_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogadmin',
            name='meta_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogadmin',
            name='subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
