# Generated by Django 5.0.3 on 2024-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0007_auto_20240319_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
