# Generated by Django 3.2.12 on 2024-03-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0008_alter_blogadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadmin',
            name='meta_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogadmin',
            name='subheading',
            field=models.CharField(max_length=100),
        ),
    ]
