# Generated by Django 3.2.12 on 2024-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0009_auto_20240321_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadmin',
            name='meta_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogadmin',
            name='subheading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
