# Generated by Django 3.2.12 on 2024-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0010_auto_20240321_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
