# Generated by Django 5.0.3 on 2024-04-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0011_auto_20240321_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogadmin',
            old_name='meta_description',
            new_name='categories',
        ),
    ]
