# Generated by Django 5.0.3 on 2024-04-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0012_rename_meta_description_blogadmin_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogadmin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teranium_project/media'),
        ),
    ]
