# Generated by Django 5.0.3 on 2024-04-30 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teranium_app', '0013_blogadmin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadmin',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
